version: '3.9'
networks:
  mc-net:
    name: mc-net
    driver: bridge
services:
  ngninx:
    container_name: mc-nginx
    restart: always
    build:
      context: .docker/local/nginx/
      dockerfile: nginx.dockerfile
    volumes:
      - .:/var/www/html
      - .docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 443:443
    networks:
      - mc-net
  mc-php:
    container_name: mc-php
    user: "1000:1000" 
    build:
      context: .docker/local/php
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
      - .xdebug_profiles:/var/www/xdebug_profiles
      - .docker/local/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mc-net
  mc-db:
    container_name: mc-db
    image: postgres:17.3-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .docker/local/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mc
    networks:
      - mc-net
