version: '3.9'
networks:
  jron-net:
    name: jron-net
    driver: bridge
services:
  ngninx:
    container_name: jron-nginx
    restart: always
    build:
      context: .docker/local/nginx/
      dockerfile: nginx.dockerfile
    volumes:
      - .:/var/www/html
      - .docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 443:443
    networks:
      - jron-net
  jron-php:
    container_name: jron-php
    build:
      context: .docker/local
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - jron-net
  jron-db:
    container_name: jron-db
    image: postgres:17.3-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .docker/local/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jron
    networks:
      - jron-net
